version: "3"

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    container_name: security-plugin-db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
